### ISSUE TITLE
Speakers for OpenConCam 2017

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#16]
Who would you like to invite to speak at OpenConCam 2017?

(Note that this will heavily depend on the theme we choose. Check out #11 for those discussions.)

**Comment by lgatto** [comment]
Given the theme (see #11), I will start with a few suggestions:
- Jon Tennant
- Bastian Greshake
- Björn Brembs
- Danny Kingsley (ideally suited to inform us on the state of open research at this institution)

**Comment by corinalogan** [comment]
Janneke Adema - disrupting the humanities, self-branding (https://openreflections.wordpress.com/author/jannekeadema1979/)

**Comment by corinalogan** [comment]
Hi all,
I've been talking with people in Germany to figure out who we should invite to OCC to talk about the DEAL. There are two suggestions:

Dr Antje Kellersohn, Director of the University Library Freiburg, Lead of the Baden-Württemberg Licensing Consortium, antje.kellersohn@ub.uni-freiburg.de
**Antje is the spokesperson of the DEAL project group** (https://www.projekt-deal.de/about-deal/)

or alternatively a team member of Antje's:
Dr Hildegard Schäffler, Bavarian State Library, Head of Serials, Licensing, Electronic Publishing, Lead of the Bavarian State Licensing Consortium, schaeffler@bsb-muenchen.de

Birgit Schmidt (a scientific manager at Goettingen State and University Library) says "Both are high regarded for their excellent work. Personally, I only know the latter, from meetings of the International Coalition of Library Consortia (ICOLC)."

**Comment by corinalogan** [comment]
If we incorporate the theme of making open more inclusive, we should invite speakers who are underrepresented minorities (URMs) so their voices are heard and we can learn how to better support them. So far I don't think we have suggested any URMs as speakers so let's get to searching!

**Comment by lgatto** [comment]
> So far I don't think we have suggested any URMs as speakers so let's get to searching!

We could ask @cbahlai or [DNlee5](https://twitter.com/DNLee5) to give a talk over google hangouts, like we did last time.

**Comment by corinalogan** [comment]
I heard from @DieterLukas that Tapoka Mkandawire (@TapokaM) gave an excellent talk at a recent Gender in STEM conference in Cambridge. Dieter suggested Tapoka might be a good speaker to invite to OpenCon Cambridge because of her experience of a thriving scientific community in Malawi that has very low representation of women, and what she is learning about how to change it. Tapoka says (in her slides) that Malawi has "one of the largest GDP to R&D spending ratios in Africa" and their "scientists publish more in mainstream journals - relative to GDP - than any other country of a similar population size". I'm not sure what her views on open research are, but we could ask. If she has something to say about it, she could add this to her talk.

**Comment by TapokaM** [comment]
Hi @corinalogan and all, you do have the correct profile, I'm a github newbie and haven't got much detail yet. Honoured to be considered for this speaking engagement. Always happy to speak about my observations and experiences of practicing STEM and Women in STEM in low and middle income countries. I work for the Wellcome Trust at the Sanger Institute here and have worked for them in Malawi so I am very much pro open research, and have seen how it can be used to drive research especially with regards to bioinformatics.

**Comment by corinalogan** [comment]
Hi @TapokaM - I'm glad it's really you and that you are interested in this event! Thank you so much for expanding on how you might fit as a speaker at OpenCon Cambridge and for sharing your views on open research! We will likely start voting on which speakers to invite later this week so stay tuned :) 

Also, in case you are interested, you would be more than welcome to join OpenConCam (http://www.openconcam.org). We meet at the OpDA postdoc centre on Mill Lane at 12:30p on the 1st Tues of the month.

**Comment by npscience** [comment]
Hi all,

Do we have a deadline for suggesting speakers? @lgatto @KirstieJane 

I'm just back from holiday and will need to find some time to think and consider options. I particularly echo the comment re inviting under-represented people to the platform. Will need to search through my contacts to add speaker suggestions on that point.

**Comment by corinalogan** [comment]
I think voting online is a great way to go.

**Comment by rollerlibrarian** [comment]
Agreed!

**Comment by npscience** [comment]
I've been thinking about speakers, particularly:
- under-represented voices
- people who have acted for open science, from big to small, a diversity of options of ow to contribute (with your own scholarship, following best open practises, community projects and advocacy)
- people with experiences to share about starting a community / maintaining a happy, inclusive, productive community / addressing issues in the open science community

Here are my suggestions to throw into the ballpark, in addition to excellent suggestions others have already made. Some are wildcards, some are people I have contacts/connections with.

* Jenny Wong (@missjwo) - she is a community manager and involved in the WordPress open source community. I saw her give an excellent talk about building an inclusive community at FOSDEM (open source tech conf) [earlier this year](https://fosdem.org/2017/schedule/event/community_building_an_accessible_community/)
Not strictly open science, but definitely openness and inclusion, and open science could learn a lot from open source community people.

* Alex Lathbridge - he was the UK FameLab finalist this year, and he raps about science as sci comms. He's an interesting one to consider regarding inclusion (apparently people don't expect him to be a scientist because they profile him), and offers [an interesting way to share your research](https://www.youtube.com/watch?v=kGxje-VC3EU)

* It would be really cool to heard from Kade Morton about alternatives to our current system - co-founder of Aletheia and one of the Mozilla Open Leaders this year [twitter](https://twitter.com/cypath)

* Lucy Patterson, based in Berlin and founder of DIYscience, another alternative way to do science (outside of academia). She could present both experiences about running a community and about opening up science [twitter](https://twitter.com/lu_cyp)

* Camille Maumet, based in Oxford, and lead for [easy fMRI reporting](https://github.com/easyreporting/fmri_reporting) - practical ways to do open neuroimaging research [http://camillemaumet.com/](http://camillemaumet.com/)

* Francesca Mancini, based in Aberdeen, and has set up a study group there for open science / best practises / learning R [her github](https://github.com/FrancescaMancini) and [academic profile](http://pure.abdn.ac.uk:8080/portal/en/persons/francesca-mancini(10db03c5-a457-47fe-8f6c-4c77b9834007).html)

* Olivia Guest, at UCL, has been pretty vocal on twitter about gender diversity in open science, also a science blogger [twitter](https://twitter.com/o_guest)

* Lisa DeBruine, diversity and open science, researcher on facial expressions (psychology) see [facelab.org](http://facelab.org/) [twitter](https://twitter.com/lisadebruine) and posts lots of research on [OSF](https://osf.io/4i578/) so appears to be an active open scientist

* Amie Fairs, Oxford, co-leader of [Why Not Open Science](https://github.com/dasaderi/WhyNotOpenScience), a survey project to understand the blockers to open science (she was at OpenCon last year, and a MozOpenLeader this year)
[twitter](https://twitter.com/amiefairs)

* Sabina Leonelli, open data (social sciences), Egenis - studies history and philoshopy of science and about open science (could give an interesting history/context to the day?)
[academic profile](http://socialsciences.exeter.ac.uk/sociology/research/sts/egenis/staff/leonelli)
[twitter](https://twitter.com/SabinaLeonelli)

* Sian Harris, works on the importance of OA to global development [twitter](https://twitter.com/SianHarris8?lang=en)

Any thoughts?

**Comment by lgatto** [comment]
Thank you for all these suggestions @npscience. Will you be able to join next week for the meeting?

**Comment by npscience** [comment]
Sadly not for Tuesday, I'm away. But I could contribute votes on Tuesday evening (maybe earlier if there's wifi on the Eurostar, anyone know?)

**Comment by lgatto** [comment]
We'll post discussions and updates here and/or on the google group.

**Comment by jcmolloy** [comment]
Emma Ganley (Lead of PLOS data program and EIC of PLOS Biology, suggested by Artur)

**Comment by lgatto** [comment]
I think we have our speakers now. Closing this issue, but anyone should feel free to open it again if necessary.
